resolver 127.0.0.11 valid=10s ipv6=off;

upstream applicant_service {
    zone applicant_service 64k;
    server applicant:80 resolve;
}

upstream reviewer_service {
    zone reviewer_service 64k;
    server reviewer:80 resolve;
}

server {
    listen 80;
    server_name _;
    client_max_body_size 10m;

    location = / {
        return 302 /interview/;
    }

    location = /interview {
        return 302 /interview/;
    }

    location /interview/ {
        proxy_pass http://applicant_service/;
    }

    location = /console {
        return 302 /console/;
    }

    location /console/ {
        proxy_pass http://reviewer_service/;
    }
}
